### ISSUE TITLE
`!tremove` does not work after the first call

### ISSUE THREAD

**Issue by kev-cao** [defCoding/queue-bot-discord#8]
## Issue
`!tremove` does not seem to delete topics correctly after the initial call, which works perfectly fine.

## Recreation
1. Create a series of multiple topics (e.g. `!tadd A | B | C | D`).
2. Run a `!tremove` command (e.g. `!tremove 3`).
3. Run another `!tremove` command (e.g. `!tremove 2`).

## Expected Behavior
1. Topics A, B, C, D are created.
2. Topic D is removed. Reaction :three: is removed from the message and the entry in the message body is crossed out.
3. Topic C is removed. Reaction :two: is removed from the message and the entry in the message body is crossed out.

## Actual Behavior
1. Topics A, B, C, D are created.
2. Topic D is removed. Reaction :three: is removed from the message and the entry in the message body is crossed out.
3. Topic C is left untouched.

Running any other `!tremove` command afterwards is responded to with "Please give a proper value" and the topic message is deleted.

**Comment by annrpom** [comment]
very thorough description - ty

**Comment by annrpom** [comment]
see PR #12

**Comment by defCoding** [comment]
https://github.com/annrpom/botTA-than-kevins-discord-bot/blob/59c1400094d39f783f47a7b8fd8ad184a752b368/bot.js#L65-L76
